services:
  incidents-primary:
    image: gcr.io/cloudsql-docker/gce-proxy:1.12
    platform: linux/amd64
    container_name: incidents-primary
    command: /cloud_sql_proxy -instances=${INSTANCE_INCIDENTS} -credential_file=/config
    ports:
      - '0.0.0.0:${PORT_INCIDENTS}:3306'
    volumes:
      - ./${JSON_KEY_FILE}:/config
    networks: [backend]
  
  incidents-replica:
    image: gcr.io/cloudsql-docker/gce-proxy:1.12
    platform: linux/amd64
    container_name: incidents-replica
    command: /cloud_sql_proxy -instances=${INSTANCE_INCIDENTS_REPLICA} -credential_file=/config
    ports:
      - '0.0.0.0:${PORT_INCIDENTS_REPLICA}:3306'
    volumes:
      - ./${JSON_KEY_FILE}:/config
    networks: [backend]
 
  redis:
    image: redis:alpine
    container_name: ${DOCKER_REDIS_SERVICE_NAME}
    networks:
      - backend
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
 
  backend:
    build:
      context: ./incidentes
      dockerfile: Dockerfile
    container_name: incidents_backend
    networks:
      - backend
    ports:
      - '${DOCKER_BACKEND_PORT}:8080'
    env_file:
      - .env
    volumes:
      - ./incidentes:/app/incidentes
      - ./.env:/app/.env
      - ./${JSON_KEY_FILE}:/app/${JSON_KEY_FILE}
 
networks:
  backend:
    external: true
    name: prueba